server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/card_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/migration/master.yaml

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

crypto:
  aes:
    secret: ${CRYPTO_SECRET}
    algorithm: AES

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json